version: "2.4"

services:

  ory-hydra-oauth2-example-client-readonly-backend:
    image: chistousov/ory-hydra-oauth2-example-client-readonly-backend:1.0.0
    container_name: ory-hydra-oauth2-example-client-readonly-backend
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en

      - BPL_JAVA_NMT_LEVEL=detail

      # health check
      - THC_PATH=/actuator/health
      - THC_PORT=8080

      - JAVA_TOOL_OPTIONS=
        -Dspring.profiles.active=prod

        -Dspring.security.oauth2.client.registration.client-readonly.client-id=${CLIENT_READONLY_CLIENT_ID}
        -Dspring.security.oauth2.client.registration.client-readonly.client-secret=${CLIENT_READONLY_CLIENT_SECRET}
        -Dspring.security.oauth2.client.registration.client-readonly.redirect-uri=https://client-readonly.com/login/oauth2/code/client-readonly
        
        -Dspring.security.oauth2.client.provider.spring.authorization-uri=https://authorization-server.com/oauth2/auth
        -Dspring.security.oauth2.client.provider.spring.token-uri=https://authorization-server.com/oauth2/token
        -Dspring.security.oauth2.client.provider.spring.user-info-uri=https://authorization-server.com/userinfo
        -Dspring.security.oauth2.client.provider.spring.user-name-attribute=sub
        
        -Dapplication.frontend.error-oauth2-page="/error"
        -Dapplication.resource-server="https://resource-server.com/api"

    user: "1005"
    mem_limit: 1G
    logging:
      options:
        max-size: "100m"
        max-file: "1"
    volumes:
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    healthcheck:
      test: "/cnb/process/health-check"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - app-network
  
  ory-hydra-oauth2-example-client-readonly-gateway-nginx:
    image: nginx:1.23.4-bullseye
    container_name: ory-hydra-oauth2-example-client-readonly-gateway-nginx
    ports:
      - 443:443
    volumes:
      - type: bind
        source: nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

      - type: bind
        source: nginx/confs
        target: /etc/nginx/conf.d
        read_only: true

      - type: bind
        source: nginx/cert
        target: /cert
        read_only: true

      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true

      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true

    restart: unless-stopped
    depends_on:
      ory-hydra-oauth2-example-client-readonly-backend:
        condition: service_healthy
    logging:
      options:
        max-size: "100m"
        max-file: "1"
    mem_limit: 1G
    networks:
      - app-network
  

networks:
  app-network: