version: "2.4"

services:

  ory-hydra-oauth2-example-resource-server-backend:
    image: chistousov/ory-hydra-oauth2-example-resource-server-backend:1.0.0
    container_name: ory-hydra-oauth2-example-resource-server-backend
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en

      - BPL_JAVA_NMT_LEVEL=detail

      # health check
      - THC_PATH=/actuator/health
      - THC_PORT=8080

      - JAVA_TOOL_OPTIONS=
        -Dspring.profiles.active=prod

        -Dspring.security.oauth2.resourceserver.opaquetoken.client-id=${HYDRA_INTROSPECT_USER}
        -Dspring.security.oauth2.resourceserver.opaquetoken.client-secret=${HYDRA_INTROSPECT_PASSWORD}
        -Dspring.security.oauth2.resourceserver.opaquetoken.introspection-uri=https://authorization-server.com/admin/oauth2/introspect
        
    user: "1005"
    mem_limit: 1G
    logging:
      options:
        max-size: "100m"
        max-file: "1"
    volumes:
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    healthcheck:
      test: "/cnb/process/health-check"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - app-network


  ory-hydra-oauth2-example-resource-server-gateway-nginx:
    image: nginx:1.23.4-bullseye
    container_name: ory-hydra-oauth2-example-resource-server-gateway-nginx
    ports:
      - 443:443
    volumes:
      - type: bind
        source: nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

      - type: bind
        source: nginx/confs
        target: /etc/nginx/conf.d
        read_only: true

      - type: bind
        source: nginx/cert
        target: /cert
        read_only: true

      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true

      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true

    restart: unless-stopped
    depends_on:
      ory-hydra-oauth2-example-resource-server-backend:
        condition: service_healthy
    logging:
      options:
        max-size: "100m"
        max-file: "1"
    mem_limit: 1G
    networks:
      - app-network

networks:
  app-network:
